name: Linux x86_64 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Clean workspace
        run: |
          rm -rf deccord

      - name: Clone Deccord repository
        run: |
          git clone https://github.com/Deccord/deccord.git
          cd deccord
          chmod -R 777 .

      - name: Setup dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y make automake cmake curl g++-multilib libtool \
            binutils-gold bsdmainutils pkg-config python3-dev patch bison \
            libxcb-xinerama0-dev libxcb-icccm4-dev x11proto-randr-dev \
            x11proto-xinerama-dev libx11-xcb-dev

      - name: Cache Depends
        uses: actions/cache@v4
        with:
          path: deccord/depends
          key: ${{ runner.os }}-depends-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-depends-

      - name: Cache Berkeley DB
        uses: actions/cache@v4
        with:
          path: deccord/db4
          key: ${{ runner.os }}-db4-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-db4-

      - name: Install Berkeley DB
        run: |
          cd deccord
          ./contrib/install_db4.sh `pwd`
          export BDB_PREFIX="${PWD}/db4"

      - name: Build depends
        run: |
          cd deccord
          PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
          cd depends
          make HOST=x86_64-pc-linux-gnu -j$(nproc)
          cd ..

      - name: Build Deccord for Linux
        run: |
          cd deccord
          ./autogen.sh
          export BDB_PREFIX="${PWD}/db4"
          CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site ./configure --prefix=/ \
            BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" \
            BDB_CFLAGS="-I${BDB_PREFIX}/include" \
            --disable-tests --disable-shared
          if [ -f "src/deccordd" ]; then
            echo "Skipping make, using cached binaries."
          else
            make -j$(nproc)
          fi

      - name: Strip Binaries
        run: |
          cd deccord
          strip src/deccordd src/deccord-cli src/deccord-tx src/qt/deccord-qt

      - name: Create tar.gz and zip archives
        run: |
          cd deccord
          mkdir -p deccord-20.0.1-x86_64-pc-linux-gnu
          cp src/deccordd src/deccord-cli src/deccord-tx src/qt/deccord-qt deccord-20.0.1-x86_64-pc-linux-gnu/
          tar -czvf deccord-20.0.1-x86_64-pc-linux-gnu.tar.gz deccord-20.0.1-x86_64-pc-linux-gnu
          zip -r deccord-20.0.1-x86_64-pc-linux-gnu.zip deccord-20.0.1-x86_64-pc-linux-gnu

      - name: Upload Linux Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deccord-linux-x86_64-build
          path: |
            deccord-20.0.1-x86_64-pc-linux-gnu.tar.gz
            deccord-20.0.1-x86_64-pc-linux-gnu.zip

      - name: Upload Partial Build Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: partial-build-${{ github.run_id }}
          path: deccord/src
