name: Build Deccord Wallet for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
      - name: Install dependencies
        run: |
          brew update
          brew install automake libtool boost gmp pkg-config libevent
          brew install llvm
          export CC=$(brew --prefix llvm)/bin/clang
          export CXX=$(brew --prefix llvm)/bin/clang++

      - name: Clone Deccord repository
        run: git clone https://github.com/Deccord/deccord.git

      - name: Set permissions for Deccord folder
        run: |
          chmod -R 777 deccord

      - name: Install optional dependencies
        run: |
          brew install berkeley-db@4 sqlite qt@5 qrencode miniupnpc libnatpmp zeromq

      - name: Build Berkeley DB 4.8
        run: |
          cd deccord/contrib
          ./install_db4.sh `pwd`
        
      - name: Set up Cross Compilation for macOS
        run: |
          export HOST=x86_64-apple-darwin
          export CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site  # Adjust based on the actual path
          
      - name: Build Deccord (Enable Wallet, Disable Test Build)
        run: |
          cd deccord
          ./autogen.sh
          ./configure --with-bdb --with-gui --without-test --without-qt-tests
          make HOST=x86_64-apple-darwin -j$(sysctl -n hw.ncpu)
        
      - name: Create the deployable .dmg
        run: |
          cd deccord
          make deploy

      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deccord-macos-build
          path: ./deccord/deploy/*.dmg
